language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - node_modules
services:
  - mongodb
script:
  - rm -rf package-lock.json node_modules 
  - npm i
  - npm install coveralls
  - npm run lint
  - npm test
after_success:
  - npm run coverage
